version: "3.8"

services:
  postgres-16:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=lideradm
      - POSTGRES_USER=igorgomes
      - POSTGRES_PASSWORD=igor
    ports:
      - '15432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'prisma', '-d']
      interval: 5s
      timeout: 2s
      retries: 20