import { prisma } from "@infra/utils/lib/prisma";

async function seed() {
  await prisma.$connect();
  await prisma.municipio.createMany({
    data: [
      {
        mun_cd_municipio: 1100015,
        mun_ds_municipio: "ALTA FLORESTA D'OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100023,
        mun_ds_municipio: "ARIQUEMES",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100031,
        mun_ds_municipio: "CABIXI",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100049,
        mun_ds_municipio: "CACOAL",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100056,
        mun_ds_municipio: "CEREJEIRAS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100064,
        mun_ds_municipio: "COLORADO DO OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100072,
        mun_ds_municipio: "CORUMBIARA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100080,
        mun_ds_municipio: "COSTA MARQUES",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100098,
        mun_ds_municipio: "ESPIGAO D OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100106,
        mun_ds_municipio: "GUAJARA-MIRIM",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100114,
        mun_ds_municipio: "JARU",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100122,
        mun_ds_municipio: "JI-PARANA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100130,
        mun_ds_municipio: "MACHADINHO D OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100148,
        mun_ds_municipio: "NOVA BRASILANDIA D OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100155,
        mun_ds_municipio: "OURO PRETO DO OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100189,
        mun_ds_municipio: "PIMENTA BUENO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100205,
        mun_ds_municipio: "PORTO VELHO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100254,
        mun_ds_municipio: "PRESIDENTE MEDICI",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100262,
        mun_ds_municipio: "RIO CRESPO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100288,
        mun_ds_municipio: "ROLIM DE MOURA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100296,
        mun_ds_municipio: "SANTA LUZIA D OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100304,
        mun_ds_municipio: "VILHENA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100320,
        mun_ds_municipio: "SAO MIGUEL DO GUAPORE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100338,
        mun_ds_municipio: "NOVA MAMORE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100346,
        mun_ds_municipio: "ALVORADA D OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100379,
        mun_ds_municipio: "ALTO ALEGRE DOS PARECIS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100403,
        mun_ds_municipio: "ALTO PARAISO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100452,
        mun_ds_municipio: "BURITIS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100502,
        mun_ds_municipio: "NOVO HORIZONTE DO OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100601,
        mun_ds_municipio: "CACAULANDIA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100700,
        mun_ds_municipio: "CAMPO NOVO DE RONDONIA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100809,
        mun_ds_municipio: "CANDEIAS DO JAMARI",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100908,
        mun_ds_municipio: "CASTANHEIRAS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100924,
        mun_ds_municipio: "CHUPINGUAIA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1100940,
        mun_ds_municipio: "CUJUBIM",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101005,
        mun_ds_municipio: "GOVERNADOR JORGE TEIXEIRA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101104,
        mun_ds_municipio: "ITAPUA DO OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101203,
        mun_ds_municipio: "MINISTRO ANDREAZZA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101302,
        mun_ds_municipio: "MIRANTE DA SERRA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101401,
        mun_ds_municipio: "MONTE NEGRO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101435,
        mun_ds_municipio: "NOVA UNIAO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101450,
        mun_ds_municipio: "PARECIS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101468,
        mun_ds_municipio: "PIMENTEIRAS DO OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101476,
        mun_ds_municipio: "PRIMAVERA DE RONDONIA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101484,
        mun_ds_municipio: "SAO FELIPE D OESTE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101492,
        mun_ds_municipio: "SAO FRANCISCO DO GUAPORE",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101500,
        mun_ds_municipio: "SERINGUEIRAS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101559,
        mun_ds_municipio: "TEIXEIROPOLIS",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101609,
        mun_ds_municipio: "THEOBROMA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101708,
        mun_ds_municipio: "URUPA",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101757,
        mun_ds_municipio: "VALE DO ANARI",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1101807,
        mun_ds_municipio: "VALE DO PARAISO",
        mun_ds_uf: "RO",
        mun_ds_estado: "RONDÔNIA",
        mun_cd_estado: 11,
      },
      {
        mun_cd_municipio: 1200013,
        mun_ds_municipio: "ACRELANDIA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200054,
        mun_ds_municipio: "ASSIS BRASIL",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200104,
        mun_ds_municipio: "BRASILEIA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200138,
        mun_ds_municipio: "BUJARI",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200179,
        mun_ds_municipio: "CAPIXABA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200203,
        mun_ds_municipio: "CRUZEIRO DO SUL",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200252,
        mun_ds_municipio: "EPITACIOLANDIA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200302,
        mun_ds_municipio: "FEIJO",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200328,
        mun_ds_municipio: "JORDAO",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200336,
        mun_ds_municipio: "MANCIO LIMA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200344,
        mun_ds_municipio: "MANOEL URBANO",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200351,
        mun_ds_municipio: "MARECHAL THAUMATURGO",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200385,
        mun_ds_municipio: "PLACIDO DE CASTRO",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200393,
        mun_ds_municipio: "PORTO WALTER",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200401,
        mun_ds_municipio: "RIO BRANCO",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200427,
        mun_ds_municipio: "RODRIGUES ALVES",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200435,
        mun_ds_municipio: "SANTA ROSA DO PURUS",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200450,
        mun_ds_municipio: "SENADOR GUIOMARD",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200500,
        mun_ds_municipio: "SENA MADUREIRA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200609,
        mun_ds_municipio: "TARAUACA",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200708,
        mun_ds_municipio: "XAPURI",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1200807,
        mun_ds_municipio: "PORTO ACRE",
        mun_ds_uf: "AC",
        mun_ds_estado: "ACRE",
        mun_cd_estado: 12,
      },
      {
        mun_cd_municipio: 1300029,
        mun_ds_municipio: "ALVARAES",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300060,
        mun_ds_municipio: "AMATURA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300086,
        mun_ds_municipio: "ANAMA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300102,
        mun_ds_municipio: "ANORI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300144,
        mun_ds_municipio: "APUI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300201,
        mun_ds_municipio: "ATALAIA DO NORTE",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300300,
        mun_ds_municipio: "AUTAZES",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300409,
        mun_ds_municipio: "BARCELOS",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300508,
        mun_ds_municipio: "BARREIRINHA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300607,
        mun_ds_municipio: "BENJAMIN CONSTANT",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300631,
        mun_ds_municipio: "BERURI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300680,
        mun_ds_municipio: "BOA VISTA DO RAMOS",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300706,
        mun_ds_municipio: "BOCA DO ACRE",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300805,
        mun_ds_municipio: "BORBA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300839,
        mun_ds_municipio: "CAAPIRANGA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1300904,
        mun_ds_municipio: "CANUTAMA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301001,
        mun_ds_municipio: "CARAUARI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301100,
        mun_ds_municipio: "CAREIRO",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301159,
        mun_ds_municipio: "CAREIRO DA VARZEA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301209,
        mun_ds_municipio: "COARI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301308,
        mun_ds_municipio: "CODAJAS",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301407,
        mun_ds_municipio: "EIRUNEPE",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301506,
        mun_ds_municipio: "ENVIRA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301605,
        mun_ds_municipio: "FONTE BOA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301654,
        mun_ds_municipio: "GUAJARA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301704,
        mun_ds_municipio: "HUMAITA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301803,
        mun_ds_municipio: "IPIXUNA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301852,
        mun_ds_municipio: "IRANDUBA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301902,
        mun_ds_municipio: "ITACOATIARA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1301951,
        mun_ds_municipio: "ITAMARATI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302009,
        mun_ds_municipio: "ITAPIRANGA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302108,
        mun_ds_municipio: "JAPURA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302207,
        mun_ds_municipio: "JURUA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302306,
        mun_ds_municipio: "JUTAI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302405,
        mun_ds_municipio: "LABREA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302504,
        mun_ds_municipio: "MANACAPURU",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302553,
        mun_ds_municipio: "MANAQUIRI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302603,
        mun_ds_municipio: "MANAUS",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302702,
        mun_ds_municipio: "MANICORE",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302801,
        mun_ds_municipio: "MARAA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1302900,
        mun_ds_municipio: "MAUES",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303007,
        mun_ds_municipio: "NHAMUNDA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303106,
        mun_ds_municipio: "NOVA OLINDA DO NORTE",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303205,
        mun_ds_municipio: "NOVO AIRAO",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303304,
        mun_ds_municipio: "NOVO ARIPUANA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303403,
        mun_ds_municipio: "PARINTINS",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303502,
        mun_ds_municipio: "PAUINI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303536,
        mun_ds_municipio: "PRESIDENTE FIGUEIREDO",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303569,
        mun_ds_municipio: "RIO PRETO DA EVA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303601,
        mun_ds_municipio: "SANTA ISABEL DO RIO NEGRO",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303700,
        mun_ds_municipio: "SANTO ANTONIO DO ICA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303809,
        mun_ds_municipio: "SAO GABRIEL DA CACHOEIRA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303908,
        mun_ds_municipio: "SAO PAULO DE OLIVENCA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1303957,
        mun_ds_municipio: "SAO SEBASTIAO DO UATUMA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304005,
        mun_ds_municipio: "SILVES",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304062,
        mun_ds_municipio: "TABATINGA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304104,
        mun_ds_municipio: "TAPAUA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304203,
        mun_ds_municipio: "TEFE",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304237,
        mun_ds_municipio: "TONANTINS",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304260,
        mun_ds_municipio: "UARINI",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304302,
        mun_ds_municipio: "URUCARA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1304401,
        mun_ds_municipio: "URUCURITUBA",
        mun_ds_uf: "AM",
        mun_ds_estado: "AMAZONAS",
        mun_cd_estado: 13,
      },
      {
        mun_cd_municipio: 1400027,
        mun_ds_municipio: "AMAJARI",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400050,
        mun_ds_municipio: "ALTO ALEGRE",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400100,
        mun_ds_municipio: "BOA VISTA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400159,
        mun_ds_municipio: "BONFIM",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400175,
        mun_ds_municipio: "CANTA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400209,
        mun_ds_municipio: "CARACARAI",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400233,
        mun_ds_municipio: "CAROEBE",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400282,
        mun_ds_municipio: "IRACEMA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400308,
        mun_ds_municipio: "MUCAJAI",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400407,
        mun_ds_municipio: "NORMANDIA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400456,
        mun_ds_municipio: "PACARAIMA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400472,
        mun_ds_municipio: "RORAINOPOLIS",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400506,
        mun_ds_municipio: "SAO JOAO DA BALIZA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400605,
        mun_ds_municipio: "SAO LUIZ",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1400704,
        mun_ds_municipio: "UIRAMUTA",
        mun_ds_uf: "RR",
        mun_ds_estado: "RORAIMA",
        mun_cd_estado: 14,
      },
      {
        mun_cd_municipio: 1500107,
        mun_ds_municipio: "ABAETETUBA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500131,
        mun_ds_municipio: "ABEL FIGUEIREDO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500206,
        mun_ds_municipio: "ACARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500305,
        mun_ds_municipio: "AFUA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500347,
        mun_ds_municipio: "AGUA AZUL DO NORTE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500404,
        mun_ds_municipio: "ALENQUER",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500503,
        mun_ds_municipio: "ALMEIRIM",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500602,
        mun_ds_municipio: "ALTAMIRA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500701,
        mun_ds_municipio: "ANAJAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500800,
        mun_ds_municipio: "ANANINDEUA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500859,
        mun_ds_municipio: "ANAPU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500909,
        mun_ds_municipio: "AUGUSTO CORREA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1500958,
        mun_ds_municipio: "AURORA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501006,
        mun_ds_municipio: "AVEIRO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501105,
        mun_ds_municipio: "BAGRE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501204,
        mun_ds_municipio: "BAIAO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501253,
        mun_ds_municipio: "BANNACH",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501303,
        mun_ds_municipio: "BARCARENA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501402,
        mun_ds_municipio: "BELEM",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501451,
        mun_ds_municipio: "BELTERRA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501501,
        mun_ds_municipio: "BENEVIDES",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501576,
        mun_ds_municipio: "BOM JESUS DO TOCANTINS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501600,
        mun_ds_municipio: "BONITO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501709,
        mun_ds_municipio: "BRAGANCA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501725,
        mun_ds_municipio: "BRASIL NOVO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501758,
        mun_ds_municipio: "BREJO GRANDE DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501782,
        mun_ds_municipio: "BREU BRANCO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501808,
        mun_ds_municipio: "BREVES",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501907,
        mun_ds_municipio: "BUJARU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1501956,
        mun_ds_municipio: "CACHOEIRA DO PIRIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502004,
        mun_ds_municipio: "CACHOEIRA DO ARARI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502103,
        mun_ds_municipio: "CAMETA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502152,
        mun_ds_municipio: "CANAA DOS CARAJAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502202,
        mun_ds_municipio: "CAPANEMA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502301,
        mun_ds_municipio: "CAPITAO POCO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502400,
        mun_ds_municipio: "CASTANHAL",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502509,
        mun_ds_municipio: "CHAVES",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502608,
        mun_ds_municipio: "COLARES",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502707,
        mun_ds_municipio: "CONCEICAO DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502756,
        mun_ds_municipio: "CONCORDIA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502764,
        mun_ds_municipio: "CUMARU DO NORTE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502772,
        mun_ds_municipio: "CURIONOPOLIS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502806,
        mun_ds_municipio: "CURRALINHO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502855,
        mun_ds_municipio: "CURUA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502905,
        mun_ds_municipio: "CURUCA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502939,
        mun_ds_municipio: "DOM ELISEU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1502954,
        mun_ds_municipio: "ELDORADO DOS CARAJAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503002,
        mun_ds_municipio: "FARO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503044,
        mun_ds_municipio: "FLORESTA DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503077,
        mun_ds_municipio: "GARRAFAO DO NORTE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503093,
        mun_ds_municipio: "GOIANESIA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503101,
        mun_ds_municipio: "GURUPA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503200,
        mun_ds_municipio: "IGARAPE-ACU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503309,
        mun_ds_municipio: "IGARAPE-MIRI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503408,
        mun_ds_municipio: "INHANGAPI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503457,
        mun_ds_municipio: "IPIXUNA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503507,
        mun_ds_municipio: "IRITUIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503606,
        mun_ds_municipio: "ITAITUBA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503705,
        mun_ds_municipio: "ITUPIRANGA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503754,
        mun_ds_municipio: "JACAREACANGA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503804,
        mun_ds_municipio: "JACUNDA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1503903,
        mun_ds_municipio: "JURUTI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504000,
        mun_ds_municipio: "LIMOEIRO DO AJURU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504059,
        mun_ds_municipio: "MAE DO RIO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504109,
        mun_ds_municipio: "MAGALHAES BARATA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504208,
        mun_ds_municipio: "MARABA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504307,
        mun_ds_municipio: "MARACANA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504406,
        mun_ds_municipio: "MARAPANIM",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504422,
        mun_ds_municipio: "MARITUBA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504455,
        mun_ds_municipio: "MEDICILANDIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504505,
        mun_ds_municipio: "MELGACO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504604,
        mun_ds_municipio: "MOCAJUBA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504703,
        mun_ds_municipio: "MOJU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504752,
        mun_ds_municipio: "MOJUÍ DOS CAMPOS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504802,
        mun_ds_municipio: "MONTE ALEGRE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504901,
        mun_ds_municipio: "MUANA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504950,
        mun_ds_municipio: "NOVA ESPERANCA DO PIRIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1504976,
        mun_ds_municipio: "NOVA IPIXUNA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505007,
        mun_ds_municipio: "NOVA TIMBOTEUA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505031,
        mun_ds_municipio: "NOVO PROGRESSO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505064,
        mun_ds_municipio: "NOVO REPARTIMENTO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505106,
        mun_ds_municipio: "OBIDOS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505205,
        mun_ds_municipio: "OEIRAS DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505304,
        mun_ds_municipio: "ORIXIMINA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505403,
        mun_ds_municipio: "OUREM",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505437,
        mun_ds_municipio: "OURILANDIA DO NORTE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505486,
        mun_ds_municipio: "PACAJA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505494,
        mun_ds_municipio: "PALESTINA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505502,
        mun_ds_municipio: "PARAGOMINAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505536,
        mun_ds_municipio: "PARAUAPEBAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505551,
        mun_ds_municipio: "PAU D ARCO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505601,
        mun_ds_municipio: "PEIXE-BOI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505635,
        mun_ds_municipio: "PICARRA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505650,
        mun_ds_municipio: "PLACAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505700,
        mun_ds_municipio: "PONTA DE PEDRAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505809,
        mun_ds_municipio: "PORTEL",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1505908,
        mun_ds_municipio: "PORTO DE MOZ",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506005,
        mun_ds_municipio: "PRAINHA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506104,
        mun_ds_municipio: "PRIMAVERA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506112,
        mun_ds_municipio: "QUATIPURU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506138,
        mun_ds_municipio: "REDENCAO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506161,
        mun_ds_municipio: "RIO MARIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506187,
        mun_ds_municipio: "RONDON DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506195,
        mun_ds_municipio: "RUROPOLIS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506203,
        mun_ds_municipio: "SALINOPOLIS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506302,
        mun_ds_municipio: "SALVATERRA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506351,
        mun_ds_municipio: "SANTA BARBARA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506401,
        mun_ds_municipio: "SANTA CRUZ DO ARARI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506500,
        mun_ds_municipio: "SANTA ISABEL DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506559,
        mun_ds_municipio: "SANTA LUZIA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506583,
        mun_ds_municipio: "SANTA MARIA DAS BARREIRAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506609,
        mun_ds_municipio: "SANTA MARIA DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506708,
        mun_ds_municipio: "SANTANA DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506807,
        mun_ds_municipio: "SANTAREM",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1506906,
        mun_ds_municipio: "SANTAREM NOVO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507003,
        mun_ds_municipio: "SANTO ANTONIO DO TAUA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507102,
        mun_ds_municipio: "SAO CAETANO DE ODIVELAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507151,
        mun_ds_municipio: "SAO DOMINGOS DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507201,
        mun_ds_municipio: "SAO DOMINGOS DO CAPIM",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507300,
        mun_ds_municipio: "SAO FELIX DO XINGU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507409,
        mun_ds_municipio: "SAO FRANCISCO DO PARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507458,
        mun_ds_municipio: "SAO GERALDO DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507466,
        mun_ds_municipio: "SAO JOAO DA PONTA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507474,
        mun_ds_municipio: "SAO JOAO DE PIRABAS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507508,
        mun_ds_municipio: "SAO JOAO DO ARAGUAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507607,
        mun_ds_municipio: "SAO MIGUEL DO GUAMA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507706,
        mun_ds_municipio: "SAO SEBASTIAO DA BOA VISTA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507755,
        mun_ds_municipio: "SAPUCAIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507805,
        mun_ds_municipio: "SENADOR JOSE PORFIRIO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507904,
        mun_ds_municipio: "SOURE",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507953,
        mun_ds_municipio: "TAILANDIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507961,
        mun_ds_municipio: "TERRA ALTA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1507979,
        mun_ds_municipio: "TERRA SANTA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508001,
        mun_ds_municipio: "TOME-ACU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508035,
        mun_ds_municipio: "TRACUATEUA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508050,
        mun_ds_municipio: "TRAIRAO",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508084,
        mun_ds_municipio: "TUCUMA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508100,
        mun_ds_municipio: "TUCURUI",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508126,
        mun_ds_municipio: "ULIANOPOLIS",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508159,
        mun_ds_municipio: "URUARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508209,
        mun_ds_municipio: "VIGIA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508308,
        mun_ds_municipio: "VISEU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508357,
        mun_ds_municipio: "VITORIA DO XINGU",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1508407,
        mun_ds_municipio: "XINGUARA",
        mun_ds_uf: "PA",
        mun_ds_estado: "PARÁ",
        mun_cd_estado: 15,
      },
      {
        mun_cd_municipio: 1600055,
        mun_ds_municipio: "SERRA DO NAVIO",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600105,
        mun_ds_municipio: "AMAPA",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600154,
        mun_ds_municipio: "PEDRA BRANCA DO AMAPARI",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600204,
        mun_ds_municipio: "CALCOENE",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600212,
        mun_ds_municipio: "CUTIAS",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600238,
        mun_ds_municipio: "FERREIRA GOMES",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600253,
        mun_ds_municipio: "ITAUBAL",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600279,
        mun_ds_municipio: "LARANJAL DO JARI",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600303,
        mun_ds_municipio: "MACAPA",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600402,
        mun_ds_municipio: "MAZAGAO",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600501,
        mun_ds_municipio: "OIAPOQUE",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600535,
        mun_ds_municipio: "PORTO GRANDE",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600550,
        mun_ds_municipio: "PRACUUBA",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600600,
        mun_ds_municipio: "SANTANA",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600709,
        mun_ds_municipio: "TARTARUGALZINHO",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1600808,
        mun_ds_municipio: "VITORIA DO JARI",
        mun_ds_uf: "AP",
        mun_ds_estado: "AMAPÁ",
        mun_cd_estado: 16,
      },
      {
        mun_cd_municipio: 1700251,
        mun_ds_municipio: "ABREULANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1700301,
        mun_ds_municipio: "AGUIARNOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1700350,
        mun_ds_municipio: "ALIANCA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1700400,
        mun_ds_municipio: "ALMAS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1700707,
        mun_ds_municipio: "ALVORADA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1701002,
        mun_ds_municipio: "ANANAS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1701051,
        mun_ds_municipio: "ANGICO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1701101,
        mun_ds_municipio: "APARECIDA DO RIO NEGRO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1701309,
        mun_ds_municipio: "ARAGOMINAS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1701903,
        mun_ds_municipio: "ARAGUACEMA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702000,
        mun_ds_municipio: "ARAGUACU",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702109,
        mun_ds_municipio: "ARAGUAINA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702158,
        mun_ds_municipio: "ARAGUANA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702208,
        mun_ds_municipio: "ARAGUATINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702307,
        mun_ds_municipio: "ARAPOEMA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702406,
        mun_ds_municipio: "ARRAIAS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702554,
        mun_ds_municipio: "AUGUSTINOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702703,
        mun_ds_municipio: "AURORA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1702901,
        mun_ds_municipio: "AXIXA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703008,
        mun_ds_municipio: "BABACULANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703057,
        mun_ds_municipio: "BANDEIRANTES DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703073,
        mun_ds_municipio: "BARRA DO OURO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703107,
        mun_ds_municipio: "BARROLANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703206,
        mun_ds_municipio: "BERNARDO SAYAO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703305,
        mun_ds_municipio: "BOM JESUS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703602,
        mun_ds_municipio: "BRASILANDIA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703701,
        mun_ds_municipio: "BREJINHO DE NAZARE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703800,
        mun_ds_municipio: "BURITI DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703826,
        mun_ds_municipio: "CACHOEIRINHA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703842,
        mun_ds_municipio: "CAMPOS LINDOS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703867,
        mun_ds_municipio: "CARIRI DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703883,
        mun_ds_municipio: "CARMOLANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703891,
        mun_ds_municipio: "CARRASCO BONITO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1703909,
        mun_ds_municipio: "CASEARA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1704105,
        mun_ds_municipio: "CENTENARIO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1704600,
        mun_ds_municipio: "CHAPADA DE AREIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1705102,
        mun_ds_municipio: "CHAPADA DA NATIVIDADE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1705508,
        mun_ds_municipio: "COLINAS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1705557,
        mun_ds_municipio: "COMBINADO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1705607,
        mun_ds_municipio: "CONCEICAO DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1706001,
        mun_ds_municipio: "COUTO MAGALHAES",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1706100,
        mun_ds_municipio: "CRISTALANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1706258,
        mun_ds_municipio: "CRIXAS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1706506,
        mun_ds_municipio: "DARCINOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707009,
        mun_ds_municipio: "DIANOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707108,
        mun_ds_municipio: "DIVINOPOLIS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707207,
        mun_ds_municipio: "DOIS IRMAOS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707306,
        mun_ds_municipio: "DUERE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707405,
        mun_ds_municipio: "ESPERANTINA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707553,
        mun_ds_municipio: "FATIMA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707652,
        mun_ds_municipio: "FIGUEIROPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1707702,
        mun_ds_municipio: "FILADELFIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1708205,
        mun_ds_municipio: "FORMOSO DO ARAGUAIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1708254,
        mun_ds_municipio: "FORTALEZA DO TABOCAO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1708304,
        mun_ds_municipio: "GOIANORTE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1709005,
        mun_ds_municipio: "GOIATINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1709302,
        mun_ds_municipio: "GUARAI",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1709500,
        mun_ds_municipio: "GURUPI",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1709807,
        mun_ds_municipio: "IPUEIRAS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1710508,
        mun_ds_municipio: "ITACAJA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1710706,
        mun_ds_municipio: "ITAGUATINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1710904,
        mun_ds_municipio: "ITAPIRATINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1711100,
        mun_ds_municipio: "ITAPORA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1711506,
        mun_ds_municipio: "JAU DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1711803,
        mun_ds_municipio: "JUARINA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1711902,
        mun_ds_municipio: "LAGOA DA CONFUSAO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1711951,
        mun_ds_municipio: "LAGOA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712009,
        mun_ds_municipio: "LAJEADO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712157,
        mun_ds_municipio: "LAVANDEIRA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712405,
        mun_ds_municipio: "LIZARDA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712454,
        mun_ds_municipio: "LUZINOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712504,
        mun_ds_municipio: "MARIANOPOLIS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712702,
        mun_ds_municipio: "MATEIROS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1712801,
        mun_ds_municipio: "MAURILANDIA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1713205,
        mun_ds_municipio: "MIRACEMA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1713304,
        mun_ds_municipio: "MIRANORTE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1713601,
        mun_ds_municipio: "MONTE DO CARMO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1713700,
        mun_ds_municipio: "MONTE SANTO DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1713809,
        mun_ds_municipio: "PALMEIRAS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1713957,
        mun_ds_municipio: "MURICILANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1714203,
        mun_ds_municipio: "NATIVIDADE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1714302,
        mun_ds_municipio: "NAZARE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1714880,
        mun_ds_municipio: "NOVA OLINDA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715002,
        mun_ds_municipio: "NOVA ROSALANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715101,
        mun_ds_municipio: "NOVO ACORDO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715150,
        mun_ds_municipio: "NOVO ALEGRE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715259,
        mun_ds_municipio: "NOVO JARDIM",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715507,
        mun_ds_municipio: "OLIVEIRA DE FATIMA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715705,
        mun_ds_municipio: "PALMEIRANTE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1715754,
        mun_ds_municipio: "PALMEIROPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716109,
        mun_ds_municipio: "PARAISO DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716208,
        mun_ds_municipio: "PARANA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716307,
        mun_ds_municipio: "PAU D ARCO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716505,
        mun_ds_municipio: "PEDRO AFONSO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716604,
        mun_ds_municipio: "PEIXE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716653,
        mun_ds_municipio: "PEQUIZEIRO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1716703,
        mun_ds_municipio: "COLMEIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1717008,
        mun_ds_municipio: "PINDORAMA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1717206,
        mun_ds_municipio: "PIRAQUE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1717503,
        mun_ds_municipio: "PIUM",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1717800,
        mun_ds_municipio: "PONTE ALTA DO BOM JESUS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1717909,
        mun_ds_municipio: "PONTE ALTA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718006,
        mun_ds_municipio: "PORTO ALEGRE DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718204,
        mun_ds_municipio: "PORTO NACIONAL",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718303,
        mun_ds_municipio: "PRAIA NORTE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718402,
        mun_ds_municipio: "PRESIDENTE KENNEDY",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718451,
        mun_ds_municipio: "PUGMIL",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718501,
        mun_ds_municipio: "RECURSOLANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718550,
        mun_ds_municipio: "RIACHINHO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718659,
        mun_ds_municipio: "RIO DA CONCEICAO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718709,
        mun_ds_municipio: "RIO DOS BOIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718758,
        mun_ds_municipio: "RIO SONO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718808,
        mun_ds_municipio: "SAMPAIO",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718840,
        mun_ds_municipio: "SANDOLANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718865,
        mun_ds_municipio: "SANTA FE DO ARAGUAIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718881,
        mun_ds_municipio: "SANTA MARIA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718899,
        mun_ds_municipio: "SANTA RITA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1718907,
        mun_ds_municipio: "SANTA ROSA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1719004,
        mun_ds_municipio: "SANTA TEREZA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720002,
        mun_ds_municipio: "SANTA TEREZINHA DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720101,
        mun_ds_municipio: "SAO BENTO DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720150,
        mun_ds_municipio: "SAO FELIX DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720200,
        mun_ds_municipio: "SAO MIGUEL DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720259,
        mun_ds_municipio: "SAO SALVADOR DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720309,
        mun_ds_municipio: "SAO SEBASTIAO DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720499,
        mun_ds_municipio: "SAO VALERIO DA NATIVIDADE",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720655,
        mun_ds_municipio: "SILVANOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720804,
        mun_ds_municipio: "SITIO NOVO DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720853,
        mun_ds_municipio: "SUCUPIRA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720903,
        mun_ds_municipio: "TAGUATINGA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720937,
        mun_ds_municipio: "TAIPAS DO TOCANTINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1720978,
        mun_ds_municipio: "TALISMA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1721000,
        mun_ds_municipio: "PALMAS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1721109,
        mun_ds_municipio: "TOCANTINIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1721208,
        mun_ds_municipio: "TOCANTINOPOLIS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1721257,
        mun_ds_municipio: "TUPIRAMA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1721307,
        mun_ds_municipio: "TUPIRATINS",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1722081,
        mun_ds_municipio: "WANDERLANDIA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 1722107,
        mun_ds_municipio: "XAMBIOA",
        mun_ds_uf: "TO",
        mun_ds_estado: "TOCANTIS",
        mun_cd_estado: 17,
      },
      {
        mun_cd_municipio: 2100055,
        mun_ds_municipio: "ACAILANDIA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100105,
        mun_ds_municipio: "AFONSO CUNHA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100154,
        mun_ds_municipio: "AGUA DOCE DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100204,
        mun_ds_municipio: "ALCANTARA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100303,
        mun_ds_municipio: "ALDEIAS ALTAS",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100402,
        mun_ds_municipio: "ALTAMIRA DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100436,
        mun_ds_municipio: "ALTO ALEGRE DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100477,
        mun_ds_municipio: "ALTO ALEGRE DO PINDARE",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100501,
        mun_ds_municipio: "ALTO PARNAIBA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100550,
        mun_ds_municipio: "AMAPA DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100600,
        mun_ds_municipio: "AMARANTE DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100709,
        mun_ds_municipio: "ANAJATUBA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100808,
        mun_ds_municipio: "ANAPURUS",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100832,
        mun_ds_municipio: "APICUM-ACU",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100873,
        mun_ds_municipio: "ARAGUANA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100907,
        mun_ds_municipio: "ARAIOSES",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2100956,
        mun_ds_municipio: "ARAME",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101004,
        mun_ds_municipio: "ARARI",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101103,
        mun_ds_municipio: "AXIXA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101202,
        mun_ds_municipio: "BACABAL",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101251,
        mun_ds_municipio: "BACABEIRA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101301,
        mun_ds_municipio: "BACURI",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101350,
        mun_ds_municipio: "BACURITUBA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101400,
        mun_ds_municipio: "BALSAS",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101509,
        mun_ds_municipio: "BARAO DE GRAJAU",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101608,
        mun_ds_municipio: "BARRA DO CORDA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101707,
        mun_ds_municipio: "BARREIRINHAS",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101731,
        mun_ds_municipio: "BELAGUA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101772,
        mun_ds_municipio: "BELA VISTA DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101806,
        mun_ds_municipio: "BENEDITO LEITE",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101905,
        mun_ds_municipio: "BEQUIMAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101939,
        mun_ds_municipio: "BERNARDO DO MEARIM",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2101970,
        mun_ds_municipio: "BOA VISTA DO GURUPI",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102002,
        mun_ds_municipio: "BOM JARDIM",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102036,
        mun_ds_municipio: "BOM JESUS DAS SELVAS",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102077,
        mun_ds_municipio: "BOM LUGAR",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102101,
        mun_ds_municipio: "BREJO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102150,
        mun_ds_municipio: "BREJO DE AREIA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102200,
        mun_ds_municipio: "BURITI",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102309,
        mun_ds_municipio: "BURITI BRAVO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102325,
        mun_ds_municipio: "BURITICUPU",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102358,
        mun_ds_municipio: "BURITIRANA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102374,
        mun_ds_municipio: "CACHOEIRA GRANDE",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102408,
        mun_ds_municipio: "CAJAPIO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102507,
        mun_ds_municipio: "CAJARI",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102556,
        mun_ds_municipio: "CAMPESTRE DO MARANHAO",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102606,
        mun_ds_municipio: "CANDIDO MENDES",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102705,
        mun_ds_municipio: "CANTANHEDE",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102754,
        mun_ds_municipio: "CAPINZAL DO NORTE",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
      {
        mun_cd_municipio: 2102804,
        mun_ds_municipio: "CAROLINA",
        mun_ds_uf: "MA",
        mun_ds_estado: "MARANHÃO",
        mun_cd_estado: 21,
      },
    ],
  });
  await prisma.$disconnect();
}

seed().catch((e) => {
  console.error(e);
  prisma.$disconnect();
});
